### ISSUE TITLE
Relation of wascap to other capability standards (under development)?

### ISSUE THREAD

**Issue by aschrijver** [waxosuit/wascap#47]
I recently bumped into a comment by an expert Kenton Varda (author of [Cap'n Proto](https://capnproto.org) protocol) on Object Capabilities on HN in reaction to some confusion regarding Cosmonic's use of "Capabilities" in the context of WASI capability-based security. The parent [brought up](https://news.ycombinator.com/item?id=36056311) several initiatives that use Capability-based today, and researching OCaps for the decentralized web (the future).

The co-author of the ActivityPub specification (Fediverse/Mastodon et al) is now working on Spritely and recommends [UCAN](https://ucan.xyz/) for using capabilities today.

Since Wasm looks a major thing for the future I was wondering if there's any connection to that work? And does wasmCloud's, or for that matter WASI's text on capabilities, need more clarification to place it in a broader context?

Note, I am not an expert on the subject, but interested because of ongoing work in the Fediverse that is trending in a different direction from Wasm seemingly.

**Comment by autodidaddict** [comment]
This is another case of overloaded terms. When WASI talks about capability-based security, it's at a fairly low level and involves techniques that prevent forgeries and allowing code to be redirected at runtime, etc.

With wasmCloud, the capabilities are higher level and refer to concepts like HTTP server, message broker, etc. Wascap is general purpose enough to allow you to embed a JWT in a wasm file for any capability strings. This works out well because we're also working on moving our interface definitions to `wit` and the component model so that we can standardize on some of the standards being worked on. You can find this higher level set of capabilities in the [WASI](https://github.com/WebAssembly/WASI/blob/main/Proposals.md) GitHub repository.

I'm also not an expert on Fediverse protocols but they seem to solve an entirely different set of problems than things like capabilities for WASI, at either high or low level.

**Comment by aschrijver** [comment]
Thank you, that is enlightening information. Do you have information (a link) on where to find the low level mechanics that WASI capability-based security uses?

**Comment by aschrijver** [comment]
Btw, I would like to mention that Spritely Goblins is coming to Wasm world once they brought Wasm support for Guile. The Goblins technology isn't about Fediverse, and is quite far-reaching in a similar extent to how Wasm may innovate software development.

See [The Heart of Spritely: Distributed Objects and Capability Security](https://spritely.institute/static/papers/spritely-core.html) and [Guile on WebAssembly project underway!](https://spritely.institute/news/guile-on-web-assembly-project-underway.html)

**Comment by aschrijver** [comment]
Thanks again. I dropped off a comment in the WASI repo, and will close this issue.

**Comment by autodidaddict** [comment]
> Btw, I would like to mention that Spritely Goblins is coming to Wasm world once they brought Wasm support for Guile. The Goblins technology isn't about Fediverse, and is quite far-reaching in a similar extent to how Wasm may innovate software development.
> 
> See [The Heart of Spritely: Distributed Objects and Capability Security](https://spritely.institute/static/papers/spritely-core.html) and [Guile on WebAssembly project underway!](https://spritely.institute/news/guile-on-web-assembly-project-underway.html)

This looks fascinating! 👁️ will have to take a look at Spritely and Goblins
